apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio
  labels:
    app: myportfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
        - name: myportfolio
          image: maradabhargavnaidu/myportfolio:8
          ports:
            - containerPort: 80
